export const countryRegulationCategories = [
  "Khusus",
  "Parsial",
  "Tidak ada",
  "Tidak diketahui",
] as const;

export type CountryRegulationCategory =
  (typeof countryRegulationCategories)[number];

export type CountryReference = {
  country: string;
  regulation: string;
  category: CountryRegulationCategory;
  source: string;
};

export const countryReferences = [
  {
    country: "Albania",
    regulation: "Law No. 124/2024 on Personal Data Protection",
    category: "Khusus",
    source: "https://idp.al/wp-content/uploads/2025/03/Law-no.124-2024.pdf",
  },
  {
    country: "Algeria",
    regulation: "Loi n\u00b0 18-07 du 10 juin 2018 relative \u00e0 la protection des personnes physiques dans le traitement des donn\u00e9es \u00e0 caract\u00e8re personnel (in French)",
    category: "Khusus",
    source: "https://www.joradp.dz/Jo2000/2018/034/FP10.pdf",
  },
  {
    country: "Andorra",
    regulation: "Law 29/2021Personal Data Protection Law",
    category: "Khusus",
    source: "https://www.bopa.ad/bopa/033119/Pagines/CGL20211115_08_58_32.aspx",
  },
  {
    country: "Angola",
    regulation: "Lei No. 22/11 da Protec\u00e7\u00e3o de Dados Pessoais de 17 de Junho (in Portuguese)",
    category: "Khusus",
    source: "https://media2.mofo.com/documents/Law_22_11_Data_Privacy_Law.pdf",
  },
  {
    country: "Antigua and Barbuda",
    regulation: "Data Protection Act 2013 (in English)",
    category: "Khusus",
    source: "http://laws.gov.ag/wp-content/uploads/2019/02/a2013-10.pdf",
  },
  {
    country: "Argentina",
    regulation: "Personal Data Protection Law No. 25,326",
    category: "Khusus",
    source: "https://www.unodc.org/cld/uploads/res/uncac/LegalLibrary/Argentina/Laws/Argentina%20Personal%20Data%20Protection%20Act%202000.pdf",
  },
  {
    country: "Armenia",
    regulation: "Law of the Republic of Armenia on the Protection of Personal Data (in English)",
    category: "Khusus",
    source: "http://www.foi.am/u_files/file/Personaldataprotectionlaw_ENG.pdf",
  },
  {
    country: "Australia",
    regulation: "Privacy Act 1988",
    category: "Khusus",
    source: "https://www.legislation.gov.au/C2004A03712/latest/versions",
  },
  {
    country: "Austria",
    regulation: "Federal Act concerning the Protection of Personal Data (DSG) (in German)",
    category: "Khusus",
    source: "https://www.ris.bka.gv.at/Dokumente/Erv/ERV_1999_1_165/ERV_1999_1_165.html",
  },
  {
    country: "Azerbaijan",
    regulation: "Law on Personal Data 2010 (in Azerbaijani)",
    category: "Khusus",
    source: "http://www.e-qanun.az/framework/19675",
  },
  {
    country: "Bahamas",
    regulation: "Data Protection (Privacy of Personal Information) Act 2003 (in English)",
    category: "Khusus",
    source: "http://laws.bahamas.gov.bs/cms/images/LEGISLATION/PRINCIPAL/2003/2003-0003/DataProtectionPrivacyofPersonalInformationAct_1.pdf",
  },
  {
    country: "Bahrain",
    regulation: "Law No. 30 of 2018 with Respect to Personal Data Protection (PDPL) and implementing resolutions",
    category: "Khusus",
    source: "https://www.mola.gov.bh/MediaManager/Media/Documents/Laws/Batch3/L3018.pdf",
  },
  {
    country: "Bangladesh",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Rancangan terbaru: Draft Personal Data Protection Ordinance, 2025",
    category: "Tidak ada",
    source: "https://iapp.org/news/a/notes-on-the-updated-global-privacy-law-and-dpa-directory-and-major-privacy-developments",
  },
  {
    country: "Barbados",
    regulation: "Data Protection Act, 2019-29",
    category: "Khusus",
    source: "https://www.gov.bb/General/data-protection-commissioner",
  },
  {
    country: "Belarus",
    regulation: "Personal Data Protection of 7 May 2021 No. 99-Z (Data Protection Law)",
    category: "Khusus",
    source: "https://cpd.by/en/national-regulation/the-belarusian-data-protection-act/",
  },
  {
    country: "Belgium",
    regulation: "Act of 30 July 2018 on the Protection of Natural Persons with Regard to the Processing of Personal Data",
    category: "Khusus",
    source: "https://www.dataprotectionauthority.be/publications/act-of-30-july-2018.pdf",
  },
  {
    country: "Belize",
    regulation: "Data Protection Act 2021",
    category: "Khusus",
    source: "https://www.nationalassembly.gov.bz/wp-content/uploads/2021/12/Act-No-45-of-2021-Data-Protection-Act.pdf",
  },
  {
    country: "Benin",
    regulation: "Loi n\u00b0 2009-09 of may 22, 2009Dealing with the protection of Personally Identifiable Information (PII) in the Republic of Benin.",
    category: "Khusus",
    source: "https://apdp.bj/wp-content/uploads/2016/08/Loi-No-2009-du-22Mai-2009-Version-Anglaise.pdf",
  },
  {
    country: "Bhutan",
    regulation: "Bhutan Information, Communications and Media Act 2018",
    category: "Parsial",
    source: "https://www.dit.gov.bt/information-communications-and-media-act-bhutan-2018",
  },
  {
    country: "Bolivia (Plurinational State of)",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Status terakhir: Bill of Personal Data Protection",
    category: "Tidak ada",
    source: "https://www.dlapiperdataprotection.com/guide.pdf?c=BO",
  },
  {
    country: "Bosnia and Herzegovina",
    regulation: "Law on Personal Data Protection (Official Gazette of BiH No. 12/2025)",
    category: "Khusus",
    source: "https://advokatskafirmasajic.com/blog/new-personal-data-protection-legislation/",
  },
  {
    country: "Botswana",
    regulation: "Data Protection Act, Act No. 18 of 2024",
    category: "Khusus",
    source: "https://botswanalaws.com/consolidated-statutes/principle-legislation/data-protection",
  },
  {
    country: "Brazil",
    regulation: "General Data Protection Law (LGPD), Federal Law no. 13,709/2018",
    category: "Khusus",
    source: "https://www.dataguidance.com/sites/default/files/lgpd_translation.pdf",
  },
  {
    country: "Bulgaria",
    regulation: "Personal Data Protection Act (\u201cPDPA\u201d)",
    category: "Khusus",
    source: "https://dv.parliament.bg/DVWeb/showMaterialDV.jsp;jsessionid=17AC48BEC0100FB28FDA0294DE0C9CC0?idMat=135056",
  },
  {
    country: "Burkina Faso",
    regulation: "Loi n\u00b0 010-2004/AN Portant Protection des Donn\u00e9es \u00e0 Caract\u00e8re Personnel (in French)",
    category: "Khusus",
    source: "http://www.afapdp.org/wp-content/uploads/2012/01/Burkina-Faso-Loi-portant-protection-des-donn%C3%A9es-%C3%A0-caract%C3%A8re-personnel-20042.pdf",
  },
  {
    country: "Cambodia",
    regulation: "Article 32 of the Law on Electronic Commerce, 2019; Draft Law on Personal Data Protection",
    category: "Parsial",
    source: "https://www.dlapiperdataprotection.com/guide.pdf?c=KH",
  },
  {
    country: "Cameroon",
    regulation: "Law No. 2024/017 of 23 December 2024 relating to personal data protection",
    category: "Khusus",
    source: "https://www.prc.cm/en/news/the-acts/laws/7602-law-no-2024-017-of-23-december-2024-to-authorize-the-president-of-the-republic-to-ratify-the-beijing-treaty-on-audio-visual-performances-adopted-in-beijing-china-on-24-june-2019",
  },
  {
    country: "Canada",
    regulation: "Personal Information Protection and Electronic Documents Act (PIPEDA)",
    category: "Khusus",
    source: "https://laws-lois.justice.gc.ca/eng/acts/P-8.6/",
  },
  {
    country: "Chad",
    regulation: "Law 007/PR/2015 on the Protection of Personal Data (in French and Arabic)",
    category: "Khusus",
    source: "https://arcep.td/sites/default/files/Loi-N%C2%B007-PR-2015.pdf",
  },
  {
    country: "Chile",
    regulation: "Law No. 19,628 as amended by Law No. 21,719 on the Protection of Personal Data",
    category: "Khusus",
    source: "https://www.carey.cl/en/law-no-21719-amending-law-no-19628-on-the-protection-of-private-life-is-published-in-the-chilean-official-gazette/",
  },
  {
    country: "China",
    regulation: "Personal Information Protection Law (PIPL)",
    category: "Khusus",
    source: "https://en.spp.gov.cn/2021-12/29/c_948419_2.htm",
  },
  {
    country: "Colombia",
    regulation: "Ley 1581 de 2012 - Marco general de la protecci\u00f3n de los datos personales en Colombia (in Spanish)",
    category: "Khusus",
    source: "https://www.funcionpublica.gov.co/eva/gestornormativo/norma_pdf.php?i=49981",
  },
  {
    country: "Congo",
    regulation: "Loi n\u00b0 29-2019 du 10 octobre 2019 portant protection des donn\u00e9es \u00e0 caract\u00e8re personnel (in French)",
    category: "Khusus",
    source: "https://www.sgg.cg/JO/2019/congo-jo-2019-45.pdf",
  },
  {
    country: "Costa Rica",
    regulation: "Law No. 8968 on the Protection of the Person Regarding the Processing of Personal Data",
    category: "Khusus",
    source: "https://www.dlapiperdataprotection.com/index.html?c=CR&t=law",
  },
  {
    country: "Croatia",
    regulation: "Act on the Implementation of the General Data Protection Regulation (in Croatian: Zakon o provedbi Op\u0107e uredbe o za\u0161titi podataka) (the \u201cImplementation Act\u201d)",
    category: "Khusus",
    source: "https://narodne-novine.nn.hr/clanci/sluzbeni/2018_05_42_805.html",
  },
  {
    country: "Cuba",
    regulation: "Personal Data Protection law (Law 149/2022)",
    category: "Khusus",
    source: "https://www.wipo.int/wipolex/en/text/586230",
  },
  {
    country: "Cyprus",
    regulation: "The Protection of Physical Persons Against the Processing of Personal Data and Free Movement of such Data Law 125(I)/2018",
    category: "Khusus",
    source: "https://www.dataprotection.gov.cy/dataprotection/dataprotection.nsf/All/2B53605103DCE4A4C225826300362211",
  },
  {
    country: "Czechia",
    regulation: "Personal Data Processing Act (Act No. 110/2019 Coll.)",
    category: "Khusus",
    source: "https://uoou.gov.cz/media/act-no-110-2019-coll.pdf",
  },
  {
    country: "C\u00f4te d'Ivoire",
    regulation: "Loi n\u00b0 2013-450 du 19 juin 2013 relative \u00e0 la protection des donn\u00e9es \u00e0 caract\u00e8re personnel (in French)",
    category: "Khusus",
    source: "http://media.mofo.com/files/PrivacyLibrary/3979/Cote-d-voire-loi_2013_450.pdf",
  },
  {
    country: "Democratic Republic of the Congo",
    regulation: "Digital Code 2023 (Title III on personal data protection)",
    category: "Parsial",
    source: "https://www.dlapiperdataprotection.com/guide.pdf?c=CD",
  },
  {
    country: "Denmark",
    regulation: "Databeskyttelsesloven (the \u201cData Protection Act\u201d)",
    category: "Khusus",
    source: "https://www.retsinformation.dk/Forms/R0710.aspx?id=201319",
  },
  {
    country: "Dominican Republic",
    regulation: "Ley No. 172-13, sobre Protecci\u00f3n de Datos de Car\u00e1cter Personal del 13 de diciembre de 2013 (in English)",
    category: "Khusus",
    source: "https://indotel.gob.do/media/6200/ley_172_13.pdf",
  },
  {
    country: "Ecuador",
    regulation: "Personal Data Protection Organic Law",
    category: "Khusus",
    source: "https://www.finanzaspopulares.gob.ec/wp-content/uploads/2021/07/ley_organica_de_proteccion_de_datos_personales.pdf",
  },
  {
    country: "Egypt",
    regulation: "Personal Data Protection Law, Law No. 151 of 2020 (in Arabic)",
    category: "Khusus",
    source: "https://mcit.gov.eg/Upcont/Documents/Reports%20and%20Documents_1232021000_Law_No_151_2020_Personal_Data_Protection.pdf",
  },
  {
    country: "El Salvador",
    regulation: "Ley de Protecci\u00f3n de Datos Personales y Habeas Data",
    category: "Khusus",
    source: "https://www.finanzaspopulares.gob.ec/wp-content/uploads/2021/07/ley_organica_de_proteccion_de_datos_personales.pdf",
  },
  {
    country: "Equatorial Guinea",
    regulation: "Law No. 1/2016, Law on Personal Data Protection",
    category: "Khusus",
    source: "https://platform.dataguidance.com/notes/equatorial-guinea-data-protection-overview",
  },
  {
    country: "Estonia",
    regulation: "Personal Data Protection Act (the \u201cPDPA\u201d)",
    category: "Khusus",
    source: "https://www.riigiteataja.ee/en/eli/523012019001/consolide",
  },
  {
    country: "Eswatini",
    regulation: "Data Protection Act No. 5 of 2022",
    category: "Khusus",
    source: "https://www.esccom.org.sz/legislation/DATA%20PROTECTION%20ACT.pdf",
  },
  {
    country: "Ethiopia",
    regulation: "Personal Data Protection Proclamation No. 1321/2024",
    category: "Khusus",
    source: "https://www.dataguidance.com/sites/default/files/personal_data_protection_proclamation_1321-2024.pdf",
  },
  {
    country: "Finland",
    regulation: "Finnish Data Protection Act (1050/2018) (the \u201cData Protection Act\u201d)",
    category: "Khusus",
    source: "https://www.finlex.fi/fi/laki/alkup/2018/20181050",
  },
  {
    country: "France",
    regulation: "French Data Protection Act (as amended by the Law No. 2018-493 of 20 June 2018 on the protection of personal data and by the Decree No. 2018-687 of 1 August 2018) (the \u201cFDPA\u201d)",
    category: "Khusus",
    source: "https://www.legifrance.gouv.fr/loda/id/LEGITEXT000006068624",
  },
  {
    country: "Gabon",
    regulation: "Loi n\u00b0001/2011 relative \u00e0 la protection des donn\u00e9es \u00e0 caract\u00e8re personnel (in French)",
    category: "Khusus",
    source: "http://www.afapdp.org/wp-content/uploads/2012/01/Gabon-Loi-relative-%C3%A0-la-protection-des-donn%C3%A9es-personnelles-du-4-mai-20112.pdf",
  },
  {
    country: "Gambia",
    regulation: "Personal Data Protection and Privacy Act, 2025",
    category: "Khusus",
    source: "https://www.africanlawbusiness.com/uncategorized/key-features-of-the-gambian-personal-data-protection-and-privacy-act/",
  },
  {
    country: "Georgia",
    regulation: "Law of Georgia on Personal Data Protection (in English)",
    category: "Khusus",
    source: "https://gc-pfiles.mfa.gov.ge/DocFiles//2023/12/14/LegalAct/31/03db4098-78f9-4449-a957-ce6995c114ae.pdf",
  },
  {
    country: "Germany",
    regulation: "Bundesdatenschutzgesetz - BDSG (in German)",
    category: "Khusus",
    source: "https://www.gesetze-im-internet.de/bdsg_2018/BJNR209710017.html",
  },
  {
    country: "Ghana",
    regulation: "Data Protection Act (Act No. 843) 2012 - DPA (in English)",
    category: "Khusus",
    source: "http://media.mofo.com/files/PrivacyLibrary/3981/GHANAbill.pdf",
  },
  {
    country: "Greece",
    regulation: "Law No. 4624/2019 Hellenic Data Protection Authority (HDPA) (in Greek)",
    category: "Khusus",
    source: "https://www.dpa.gr/APDPXPortlets/htdocs/documentSDisplay.jsp?docid=66,121,83,229,125,127,247,242",
  },
  {
    country: "Grenada",
    regulation: "Data Protection Act, No. 1 of 2023",
    category: "Khusus",
    source: "https://grenadaparliament.gd/ova_doc/data-protection-bill-08032023-with-final-hor-amendments/",
  },
  {
    country: "Guatemala",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Status terakhir: legislative initiative no. 5971",
    category: "Tidak ada",
    source: "https://www-congreso-gob-gt.translate.goog/detalle_pdf/iniciativas/5971?_x_tr_sl=es&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc#gsc.tab=0",
  },
  {
    country: "Guinea",
    regulation: "Loi L/2016/037/AN relative \u00e0 la cyber-s\u00e9curit\u00e9 et la protection des donn\u00e9es \u00e0 caract\u00e8re personnel (in French)",
    category: "Khusus",
    source: "https://mpten.gov.gn/wp-content/uploads/2019/06/loi_l2016037an_relative_a_la_cybersecurite_et_protection_des_do.pdf",
  },
  {
    country: "Guyana",
    regulation: "Data Protection Act 18 of 2023",
    category: "Khusus",
    source: "https://www.parliament.gov.gy/publications/acts-of-parliament/dataprotectionact18of2023",
  },
  {
    country: "Honduras",
    regulation: "Law for Transparency and Access to Public Information (Decree No. 170-2006) and draft personal data protection law",
    category: "Parsial",
    source: "https://www.dlapiperdataprotection.com/index.html?c=HN&t=law",
  },
  {
    country: "Hungary",
    regulation: "Act CXII of 2011 on the right to informational self-determination and on the freedom of information (in Hungarian)",
    category: "Khusus",
    source: "http://njt.hu/translated/doc/J2011T0112P_20200101_FIN.PDF",
  },
  {
    country: "Iceland",
    regulation: "Act No. 90/2018 on Data Protection and the Processing of Personal Data (in Icelandic: L\u00f6g nr. 90/2018 um pers\u00f3nuvernd og vinnslu pers\u00f3nuuppl\u00fdsinga) (the \u201cData Protection Act\u201d)",
    category: "Khusus",
    source: "https://www.althingi.is/lagas/149a/2018090.html",
  },
  {
    country: "India",
    regulation: "Digital Personal Data Protection Act, 2023 and Digital Personal Data Protection Rules, 2025",
    category: "Khusus",
    source: "https://www.meity.gov.in/static/uploads/2024/06/2bf1f0e9f04e6fb4f8fef35e82c42aa5.pdf | https://www.meity.gov.in/static/uploads/2025/11/53450e6e5dc0bfa85ebd78686cadad39.pdf",
  },
  {
    country: "Indonesia",
    regulation: "Law No. 27 of 2022 on Personal Data Protection (PDP Law)",
    category: "Khusus",
    source: "https://jdih.setkab.go.id/PUUdoc/176837/Salinan_UU_Nomor_27_Tahun_2022.pdf",
  },
  {
    country: "Iran (Islamic Republic of)",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Status terakhir: Bill on Protection of Data and Privacy in Cyberspace",
    category: "Tidak ada",
    source: "https://www.dlapiperdataprotection.com/guide.pdf?c=IR",
  },
  {
    country: "Ireland",
    regulation: "Data Protection Act 2018 (the \u201c2018 Act\u201d)",
    category: "Khusus",
    source: "https://www.irishstatutebook.ie/eli/2018/act/7/enacted/en/print",
  },
  {
    country: "Israel",
    regulation: "Protection of Privacy Law, 1981, as amended including Amendment No. 13 (2024)",
    category: "Khusus",
    source: "https://www.gov.il/BlobFolder/legalinfo/legislation/en/ProtectionofPrivacyLaw57411981unofficialtranslatio.pdf | https://www.gov.il/BlobFolder/legalinfo/the_board_role/en/Role_of_the_Board.pdf",
  },
  {
    country: "Italy",
    regulation: "Legislative Decree No. 101/2018 setting out rules adapting Italian law to the GDPR, which amended Legislative Decree No. 196/2003 setting out the Italian privacy code (the \u201cItalian Privacy Code\u201d)",
    category: "Khusus",
    source: "https://www.gazzettaufficiale.it/atto/serie_generale/caricaDettaglioAtto/originario?atto.dataPubblicazioneGazzetta=2018-09-04&atto.codiceRedazionale=18G00129&elenco30giorni=true",
  },
  {
    country: "Jamaica",
    regulation: "Data Protection Act 2020",
    category: "Khusus",
    source: "https://japarliament.gov.jm/attachments/article/341/The%20Data%20Protection%20Act,%202020%20No.%207.pdf",
  },
  {
    country: "Japan",
    regulation: "Act on the Protection of Personal Information (Act No. 57 of 2003; the \u201cAPPI\u201d)",
    category: "Khusus",
    source: "http://www.cas.go.jp/jp/seisaku/hourei/data/APPI.pdf",
  },
  {
    country: "Jordan",
    regulation: "Personal Data Protection Law No. (24) of 2023",
    category: "Khusus",
    source: "https://www.modee.gov.jo/ebv4.0/root_storage/en/eb_list_page/pdpl.pdf",
  },
  {
    country: "Kazakhstan",
    regulation: "Law No.94-V ZRK of 21 May 2013 on the Protection of Personal Data.",
    category: "Khusus",
    source: "http://www.ilo.ch/dyn/natlex/docs/ELECTRONIC/96710/143635/F-393049228/KAZ-96710.pdf",
  },
  {
    country: "Kenya",
    regulation: "The Data Protection Act, 2019 (in English)",
    category: "Khusus",
    source: "http://kenyalaw.org/kl/fileadmin/pdfdownloads/Acts/2019/TheDataProtectionAct__No24of2019.pdf",
  },
  {
    country: "Kuwait",
    regulation: "Decision No. 42 of 2021 on Data Privacy Protection Regulation and sectoral rules",
    category: "Parsial",
    source: "https://www.citra.gov.kw/sites/en/LegalReferences/Data_Privacy_Protection_Regulation.pdf",
  },
  {
    country: "Lao People's Democratic Republic",
    regulation: "Law on Electronic Data Protection",
    category: "Khusus",
    source: "https://laoofficialgazette.gov.la/kcfinder/upload/files/0918570.pdf",
  },
  {
    country: "Latvia",
    regulation: "Personal Data Processing Law",
    category: "Khusus",
    source: "https://likumi.lv/ta/en/en/id/300099-personal-data-processing-law",
  },
  {
    country: "Lebanon",
    regulation: "Law No. 81/2018 on Electronic Transactions and Personal Data",
    category: "Parsial",
    source: "https://smex.org/wp-content/uploads/2018/10/E-transaction-law-Lebanon-Official-Gazette-English.pdf",
  },
  {
    country: "Lesotho",
    regulation: "Data Protection Act No. 19 2012 (in English)",
    category: "Khusus",
    source: "http://www.nic.ls/lsnic/community/policies/Data_Protection_Act_2011_Lesotho.pdf",
  },
  {
    country: "Liechtenstein",
    regulation: "Datenschutzgesetz (the \u201cData Protection Act\u201d)",
    category: "Khusus",
    source: "https://www.gesetze.li/konso/2018272000?search_text=datenschutz&search_loc=titel&lrnr=&lgblid_von=&observe_date=11.04.2019",
  },
  {
    country: "Lithuania",
    regulation: "Law on Legal Protection of Personal Data (in English)",
    category: "Khusus",
    source: "http://www.wipo.int/wipolex/en/text.jsp?file_id=202094",
  },
  {
    country: "Luxembourg",
    regulation: "Law of 1 August 2018 organising the National Commission on Data Protection and implementing the GDPR (the \u201cData Protection Law\u201d)",
    category: "Khusus",
    source: "https://legilux.public.lu/eli/etat/leg/loi/2018/08/01/a686/jo",
  },
  {
    country: "Madagascar",
    regulation: "Law No. 38/2014 Protection of personal data (in French)",
    category: "Khusus",
    source: "http://www.afapdp.org/wp-content/uploads/2015/01/Madagascar-L-2014-038-du-09-01-15-sur-la-protection-des-donn%C3%A9es-%C3%A0-caract%C3%A8re-personnel.pdf",
  },
  {
    country: "Malawi",
    regulation: "Data Protection Act, 2024",
    category: "Khusus",
    source: "https://www.michalsons.com/blog/the-malawi-data-protection-act/74234",
  },
  {
    country: "Malaysia",
    regulation: "Personal Data Protection Act 2010, as amended by the Personal Data Protection (Amendment) Act 2024",
    category: "Khusus",
    source: "https://www.pdp.gov.my/ppdpv1/en/akta/personal-data-protection-amendment-act-2024/",
  },
  {
    country: "Maldives",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Status terakhir: Privacy and Personal Data Protection Bill (draft)",
    category: "Tidak ada",
    source: "https://www.environment.gov.mv/v2/en/download/20154",
  },
  {
    country: "Mali",
    regulation: "Loi sur la protection des donn\u00e9es \u00e0 caract\u00e8re personnel - Loi n\u00b0 2013-015 du 21 mai 2013 (in French)",
    category: "Khusus",
    source: "http://www.afapdp.org/wp-content/uploads/2012/01/Mali-Loi-sur-la-protection-des-donn%C3%A9es-personnelles-du-21-mai-2013.pdf",
  },
  {
    country: "Malta",
    regulation: "Data Protection Act, Cap 586 (in English)",
    category: "Khusus",
    source: "https://maltacvs.org/wp-content/uploads/2019/05/Data-Protection-Act.pdf",
  },
  {
    country: "Mauritania",
    regulation: "Loi 2017-020 sur la protection des donn\u00e9es \u00e0 caract\u00e8re personnel (in French)",
    category: "Khusus",
    source: "http://tic.gov.mr/IMG/pdf/imp1fr-2.pdf",
  },
  {
    country: "Mauritius",
    regulation: "Data Protection Act No. 20/2017 (in English)",
    category: "Khusus",
    source: "https://www.ilo.org/dyn/natlex/docs/ELECTRONIC/108724/134563/F686980207/MUS108724.pdf",
  },
  {
    country: "Mexico",
    regulation: "Federal Law on Protection of Personal Data Held by Private Parties (LFPDPPP)",
    category: "Khusus",
    source: "https://www.duanemorris.com/site/static/Mexico_Federal_Protection_Law_Personal_Data.pdf",
  },
  {
    country: "Monaco",
    regulation: "Law No. 1.565 of 3 December 2024 on the protection of personal data",
    category: "Khusus",
    source: "https://www.gouv.mc/en/news/monaco-adopts-personal-data-protection-legislation-in-line-with-the-highest-european-standards",
  },
  {
    country: "Mongolia",
    regulation: "Law of Mongolia on Personal Data Protection (the \u201cData Protection Law\u201d)",
    category: "Khusus",
    source: "https://www.iaac.mn/old/pdf/law_en/6_law_on_the_information_transparency_and_right_to_information.pdf",
  },
  {
    country: "Montenegro",
    regulation: "Law on Protection of Personal Data No. 79/2009, 70/2009, 44/2012, 22/2017 (in English)",
    category: "Khusus",
    source: "http://www.afapdp.org/wp-content/uploads/2012/01/Mont%C3%A9n%C3%A9gro-Personal-Data-Protection-Law-79-08-and-70-09.pdf",
  },
  {
    country: "Morocco",
    regulation: "Law No. 09-08/2009 on the protection of people toward data protection of a personal nature (in French)",
    category: "Khusus",
    source: "https://www.dgssi.gov.ma/sites/default/files/attached_files/loi_09-08protection_donnees_personnelles.pdf",
  },
  {
    country: "Namibia",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Status terakhir: draft Data Protection Bill 2022",
    category: "Tidak ada",
    source: "https://action-namibia.org/wp-content/uploads/2022/10/Data-Protection-Draft-Bill-March-2022....pdf",
  },
  {
    country: "Nepal",
    regulation: "Individual Privacy Act, 2018 (2075)",
    category: "Khusus",
    source: "http://www.lawcommission.gov.np/en/wp-content/uploads/2019/07/The-Privacy-Act-2075-2018.pdf",
  },
  {
    country: "Netherlands",
    regulation: "Uitvoeringswet Algemene Verordening Gegevensbescherming (General Data Protection Regulation Implementation Act) (the \u201cData Protection Act\u201d)",
    category: "Khusus",
    source: "https://wetten.overheid.nl/BWBR0040940/2019-02-19",
  },
  {
    country: "New Zealand",
    regulation: "Privacy Act 2020",
    category: "Khusus",
    source: "https://www.legislation.govt.nz/act/public/2020/0031/latest/LMS23223.html",
  },
  {
    country: "Nicaragua",
    regulation: "Ley No. 787 Ley de Protecci\u00f3n de Datos Personales (in Spanish)",
    category: "Khusus",
    source: "http://legislacion.asamblea.gob.ni/normaweb.nsf/9e314815a08d4a6206257265005d21f9/e5d37e9b4827fc06062579ed0076ce1d",
  },
  {
    country: "Niger",
    regulation: "Loi n\u00b02017-28 du 03 Mai 2017 relative \u00e0 la protection des donn\u00e9es \u00e0 caract\u00e8re personnel, r\u00e9vis\u00e9 en 2019 (in French)",
    category: "Khusus",
    source: "https://www.afapdp.org/wp-content/uploads/2017/02/Loi-n%c2%b02017-28-du-03-mai-2017.pdf",
  },
  {
    country: "Nigeria",
    regulation: "Nigerian Data Protection Act 2023 (in English)",
    category: "Khusus",
    source: "https://placng.org/i/wp-content/uploads/2023/06/Nigeria-Data-Protection-Act-2023.pdf",
  },
  {
    country: "North Macedonia",
    regulation: "Law on Personal Data Protection (Official Gazette of the Republic of North Macedonia, no. 42/20 and 294/21, \u201cDP Law\u201d)",
    category: "Khusus",
    source: "https://www.refworld.org/pdfid/6290d1814.pdf",
  },
  {
    country: "Norway",
    regulation: "Personal Data Act 2018 (in Norwegian)",
    category: "Khusus",
    source: "Lov om behandling av personopplysninger (personopplysningsloven) - Lovdata",
  },
  {
    country: "Oman",
    regulation: "Personal Data Protection Law issued by Royal Decree 6/22",
    category: "Khusus",
    source: "https://mola.gov.om/Download.aspx?Path=royal/2022-0006%20Formatted.pdf",
  },
  {
    country: "Pakistan",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Status terakhir: Personal Data Protection Bill 2021",
    category: "Tidak ada",
    source: "https://moitt.gov.pk/SiteImage/Misc/files/25821%20DPA%20Bill%20Consultation%20Draft(1).pdf",
  },
  {
    country: "Panama",
    regulation: "Law No. 81 of 2019 on Personal Data Protection",
    category: "Khusus",
    source: "https://www.dlapiperdataprotection.com/guide.pdf?c=PA",
  },
  {
    country: "Paraguay",
    regulation: "Personal Data Protection Law No. 7593/2025",
    category: "Khusus",
    source: "https://www.ferrere.com/en/news/paraguay-adopts-personal-data-protection-law/",
  },
  {
    country: "Peru",
    regulation: "Law No. 29733 on Personal Data Protection and Supreme Decree No. 016-2024-JUS",
    category: "Khusus",
    source: "https://www.dlapiperdataprotection.com/index.html?c=PE&t=law",
  },
  {
    country: "Philippines",
    regulation: "Republic act 10173 data privacy act of 2012",
    category: "Khusus",
    source: "http://www.lawphil.net/statutes/repacts/ra2012/ra_10173_2012.html",
  },
  {
    country: "Poland",
    regulation: "Act of 10 May 2018 on the Protection of Personal Data",
    category: "Khusus",
    source: "https://uodo.gov.pl/en/660/1464",
  },
  {
    country: "Portugal",
    regulation: "Law No. 58/2019 implementing the GDPR in Portugal",
    category: "Khusus",
    source: "https://www.dlapiperdataprotection.com/index.html?c=PT&t=law",
  },
  {
    country: "Qatar",
    regulation: "Law No. 13 of 2016 Concerning Privacy and Protection of Personal Data (in Arabic)",
    category: "Khusus",
    source: "https://www.ilo.org/dyn/natlex/natlex4.detail?p_lang=en&p_isn=105417&p_country=QAT&p_classification=01",
  },
  {
    country: "Republic of Korea",
    regulation: "Personal Information Protection Act, 2020",
    category: "Khusus",
    source: "https://elaw.klri.re.kr/eng_service/lawView.do?hseq=53044&lang=ENG",
  },
  {
    country: "Republic of Moldova",
    regulation: "Law No. 195/2024 on Personal Data Protection",
    category: "Khusus",
    source: "https://datepersonale.md/wp-content/uploads/2024/09/Law-no.-195-2024-on-personal-data-protection-1.pdf",
  },
  {
    country: "Romania",
    regulation: "Law No. 190/2018 on measures implementing the GDPR",
    category: "Khusus",
    source: "https://www.dataprotection.ro/index.jsp?lang=en&page=Legea_nr_190_2018",
  },
  {
    country: "Russian Federation",
    regulation: "Federal Law No. 152-FZ on Personal Data",
    category: "Khusus",
    source: "https://cis-legislation.com/document.fwx?rgn=13749",
  },
  {
    country: "Rwanda",
    regulation: "Law n\u00b0058/2021 of 13/10/2021 relating to the protection of personal data and privacy (the \u201cData Protection Law\u201d).",
    category: "Khusus",
    source: "https://www.dataguidance.com/sites/default/files/rw-government-gazette-dated-2021-10-15-no-special.pdf",
  },
  {
    country: "Saint Kitts and Nevis",
    regulation: "Data Protection Act 2018 (in English)",
    category: "Khusus",
    source: "https://www.dataguidance.com/sites/default/files/data_protection_act_5_of_2018.pdf",
  },
  {
    country: "Saint Lucia",
    regulation: "Data Protection Act, No 11 of 2011",
    category: "Khusus",
    source: "https://www.dataguidance.com/sites/default/files/act_11_of_2011.pdf",
  },
  {
    country: "Saint Vincent and the Grenadines",
    regulation: "Privacy Act, 2003",
    category: "Khusus",
    source: "https://www.worldlii.org/int/other/NDPrivLegis/2003/3.pdf",
  },
  {
    country: "San Marino",
    regulation: "Law No. 171 of 21 December 2018, Protection of Natural Persons with Regard to the Processing of Personal Data ('the Law')",
    category: "Khusus",
    source: "https://www.dataguidance.com/sites/default/files/law_21_december_2018_no._171_en.pdf",
  },
  {
    country: "Sao Tome and Principe",
    regulation: "Data Protection Law 2016. Lei N\u00b0 3/2016 - Protec\u00e7\u00e3o de Dados Pessoais (in Portuguese)",
    category: "Khusus",
    source: "https://www2.camara.leg.br/saotomeeprincipe/diarios-da-an/x-legislatura/ii-serie/3.a-sessao-legislativa/DAN01-IIS.pdf/view",
  },
  {
    country: "Saudi Arabia",
    regulation: "Personal Data Protection Law (PDPL) and Implementing Regulations",
    category: "Khusus",
    source: "https://dgp.sdaia.gov.sa/wps/portal/pdp/knowledgecenter/details/GPDPL/",
  },
  {
    country: "Senegal",
    regulation: "LOI n\u00b0 2008-12 du 25 janvier 2008 portant sur la Protection des donn\u00e9es \u00e0 caract\u00e8re personnel (in French)",
    category: "Khusus",
    source: "http://www.centif.sn/Loi_2008_12.pdf",
  },
  {
    country: "Serbia",
    regulation: "Data Protection Act (in English)",
    category: "Khusus",
    source: "Refworld | Serbia: 2018 Law on Personal Data Protection",
  },
  {
    country: "Seychelles",
    regulation: "Data Protection Act, 2023 (Act 24 of 2023)",
    category: "Khusus",
    source: "https://www.gazette.sc/sites/default/files/2023-12/Act%2024%20-%202023%20-%20Data%20Protection%20Act%202023.pdf",
  },
  {
    country: "Singapore",
    regulation: "Personal Data Protection (Amendment) Act 2020",
    category: "Khusus",
    source: "https://sso.agc.gov.sg/Acts-Supp/40-2020/",
  },
  {
    country: "Slovakia",
    regulation: "Act No. 18/2018 Coll., on the Protection of Personal Data and on Changing and Amending of Other Acts (the \u201cData Protection Act\u201d)",
    category: "Khusus",
    source: "https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2018/18/20180525",
  },
  {
    country: "Slovenia",
    regulation: "Personal Data Protection Act (Zakon o varstvu osebnih podatkov; ZVOP-1) (the \u201cCurrent Data Protection Act\u201d)",
    category: "Khusus",
    source: "http://pisrs.si/Pis.web/pregledPredpisa?id=ZAKO3906",
  },
  {
    country: "Somalia",
    regulation: "Law no. 005 of 2023, Data protection Act",
    category: "Khusus",
    source: "https://www.dataguidance.com/sites/default/files/somalia_data_protection_act-2.pdf",
  },
  {
    country: "South Africa",
    regulation: "Protection of Personal Information Act 4 of 2013 (in English)",
    category: "Khusus",
    source: "https://www.gov.za/sites/default/files/gcis_document/201409/3706726-11act4of2013protectionofpersonalinforcorrect.pdf",
  },
  {
    country: "Spain",
    regulation: "Ley Org\u00e1nica 3/2018, de 5 de diciembre, de Protecci\u00f3n de Datos Personales y garant\u00eda de los derechos digitales (in Spanish)",
    category: "Khusus",
    source: "https://www.boe.es/eli/es/lo/2018/12/05/3/con",
  },
  {
    country: "Sri Lanka",
    regulation: "Personal Data Protection Act No. 9 of 2022, as amended by Personal Data Protection (Amendment) Act No. 22 of 2025",
    category: "Khusus",
    source: "https://www.parliament.lk/uploads/acts/gbills/english/6242.pdf | https://www.dpa.gov.lk/",
  },
  {
    country: "Suriname",
    regulation: "Belum ada UU PDP komprehensif yang berlaku. Status terakhir: Privacy and Data Protection (SPDP) Law (draft)",
    category: "Tidak ada",
    source: "https://dpocaribbean.com/privacy-laws",
  },
  {
    country: "Sweden",
    regulation: "The Swedish Data Protection Act (2018:218) (Swe. lag (2018:218) med kompletterande best\u00e4mmelser till EU:s dataskyddsf\u00f6rordning) (the \u201dData Protection Act\u201d)",
    category: "Khusus",
    source: "https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-2018218-med-kompletterande-bestammelser_sfs-2018-218",
  },
  {
    country: "Switzerland",
    regulation: "The Federal Act on Data Protection (FADP)",
    category: "Khusus",
    source: "https://www.fedlex.admin.ch/eli/cc/2022/491/en",
  },
  {
    country: "Syrian Arab Republic",
    regulation: "Law No. 12 (2024) on protecting E- personal data",
    category: "Khusus",
    source: "https://www.pministry.gov.sy/contents/28494/\u0627\u0644\u0642\u0627\u0646\u0648\u0646-\u0631\u0642\u0645-/-12/-\u0644\u0639\u0627\u0645-2024-\u0627\u0644\u062e\u0627\u0635-\u0628\u062d\u0645\u0627\u064a\u0629-\u0627\u0644\u0628\u064a\u0627\u0646\u0627\u062a-\u0627\u0644\u0634\u062e\u0635\u064a\u0629-\u0627\u0644\u0625\u0644\u0643\u062a\u0631\u0648\u0646\u064a\u0629-\u0639\u0644\u0649-\u0627\u0644\u0634\u0628\u0643\u0629\u060c-\u0628\u0647\u062f\u0641-\u0627\u0644\u062d\u0641\u0627\u0638-\u0639\u0644\u0649-\u062e\u0635\u0648\u0635\u064a\u0629-\u0628\u064a\u0627\u0646\u0627\u062a-\u0627\u0644\u0645\u0648\u0627\u0637\u0646\u064a\u0646#:~:text=%E2%80%8C\u062c-%20\u0625\u0644\u0632\u0627\u0645%20\u0627\u0644\u0645\u0624\u0633\u0633\u0627\u062a%20\u0648\u0627\u0644\u062c\u0647\u0627\u062a%20\u0648\u0627\u0644\u0623\u0641\u0631\u0627\u062f,\u0628\u0635\u064a\u063a\u062a\u0647\u0627%20\u0627\u0644\u0625\u0644\u0643\u062a\u0631\u0648\u0646\u064a\u0629%20\u0627\u0644\u0645\u0646\u0634\u0648\u0631\u0629%20\u0639\u0644\u0649%20\u0627\u0644\u0634\u0628\u0643\u0629.",
  },
  {
    country: "Tajikistan",
    regulation: "Law of the Republic of Tajikistan No 1537 about Personal Data Protection, 2018",
    category: "Khusus",
    source: "https://cis-legislation.com/document.fwx?rgn=108952",
  },
  {
    country: "Thailand",
    regulation: "Personal Data Protection Act, B. E. 2562, 2019 (in Thai)",
    category: "Khusus",
    source: "https://www.etda.or.th/app/webroot/content_files/13/files/The%20Personal%20Data%20Protection%20Act.pdf",
  },
  {
    country: "Togo",
    regulation: "Loi No. 14/2019 relativbe a la protection des donnees a caractere personnelle (In French)",
    category: "Khusus",
    source: "https://jo.gouv.tg/sites/default/files/JO/JOS_29_10_2019-64E%20ANNEE-N%C2%B026%20TER.pdf#page=1",
  },
  {
    country: "Trinidad and Tobago",
    regulation: "Data Protection Act 2011 (in English)",
    category: "Khusus",
    source: "http://www.ttparliament.org/legislations/a2011-13.pdf",
  },
  {
    country: "Tunisia",
    regulation: "Loi organique No. 63/2004 portant sur la protection des donn\u00e9es \u00e0 caract\u00e8re personnelles (in Arabic)",
    category: "Khusus",
    source: "http://www.ins.tn/sites/default/files/Loi%2063-2004%20Fr.pdf",
  },
  {
    country: "Turkmenistan",
    regulation: "Law on Information on Private Life and its Protection No. 519-V (in Russian)",
    category: "Khusus",
    source: "https://www.ilo.org/dyn/natlex/docs/ELECTRONIC/107056/131641/F419973633/519.pdf",
  },
  {
    country: "T\u00fcrkiye",
    regulation: "Law No. 6698 on the Protection of Personal Data, as amended in 2024",
    category: "Khusus",
    source: "https://www.kvkk.gov.tr/Icerik/6649/Personal-Data-Protection-Law",
  },
  {
    country: "Uganda",
    regulation: "The Data Protection and Privacy Act 2019 (in English)",
    category: "Khusus",
    source: "https://ict.go.ug/wp-content/uploads/2019/03/Data-Protection-and-Privacy-Act-2019.pdf",
  },
  {
    country: "Ukraine",
    regulation: "Law of Ukraine No. 2297 VI 'On Personal Data Protection",
    category: "Khusus",
    source: "https://www.ilo.org/dyn/natlex/docs/ELECTRONIC/87898/103340/F-1394242499/PDF87898_eng.pdf",
  },
  {
    country: "United Arab Emirates",
    regulation: "Federal Decree-Law No. 45 of 2021 on the Protection of Personal Data",
    category: "Khusus",
    source: "https://u.ae/en/about-the-uae/digital-uae/data/data-protection-laws",
  },
  {
    country: "United Kingdom of Great Britain and Northern Ireland",
    regulation: "UK GDPR and Data Protection Act 2018, as amended by the Data (Use and Access) Act 2025",
    category: "Khusus",
    source: "https://www.legislation.gov.uk/ukpga/2018/12/contents/enacted | https://www.legislation.gov.uk/ukpga/2025/18",
  },
  {
    country: "United Republic of Tanzania",
    regulation: "The Personal Data Protection Act No. 11 of 2022 (the Act)",
    category: "Khusus",
    source: "https://oagmis.agctz.go.tz/portal/acts/237",
  },
  {
    country: "United States of America",
    regulation: "FTC Act section 5 plus state privacy laws, including California CCPA/CPRA",
    category: "Parsial",
    source: "https://oag.ca.gov/privacy/ccpa",
  },
  {
    country: "Uruguay",
    regulation: "La Ley 18.331 Protecci\u00f3n de Datos Personales y Acci\u00f3n de Habeas Data del 11 agosto del a\u00f1o 2008 y el Decreto reglamentario 414/2009 (in Spanish)",
    category: "Khusus",
    source: "https://www.impo.com.uy/bases/leyes/18331-2008",
  },
  {
    country: "Uzbekistan",
    regulation: "Law No. ZRU-547, On Personal Data, dated 2 July 2019 (in Russian)",
    category: "Khusus",
    source: "https://cis-legislation.com/document.fwx?rgn=116961",
  },
  {
    country: "Viet Nam",
    regulation: "Law No. 91/2025/QH15 on Personal Data Protection and Decree No. 356/2025/ND-CP",
    category: "Khusus",
    source: "https://vanban.chinhphu.vn/?classid=1&docid=214590&pageid=27160&typegroupid=3 | https://vanban.chinhphu.vn/?docid=216387&pageid=27160",
  },
  {
    country: "Yemen",
    regulation: "Law of the Right of Access to Information 2012",
    category: "Parsial",
    source: "http://www.right2info.org/resources/publications/laws-1/laws_yemen",
  },
  {
    country: "Zambia",
    regulation: "Data Protection Act, 2021 (in English)",
    category: "Khusus",
    source: "https://www.parliament.gov.zm/sites/default/files/documents/acts/Act%20No.%203%20The%20Data%20Protection%20Act%202021_0.pdf",
  },
  {
    country: "Zimbabwe",
    regulation: "Data Protection Act (in English)",
    category: "Khusus",
    source: "https://www.veritaszim.net/sites/veritas_d/files/Data%20Protection%20Act%205%20of%202021.pdf",
  },
] as const satisfies CountryReference[];

export function lookupCountryReference(country: string | null | undefined) {
  const normalized = normalizeCountry(country);

  if (!normalized) {
    return undefined;
  }

  const aliases: Record<string, string> = {
    korea: "republicofkorea",
    southkorea: "republicofkorea",
    singapura: "singapore",
    uk: "unitedkingdomofgreatbritainandnorthernireland",
    unitedkingdom: "unitedkingdomofgreatbritainandnorthernireland",
    usa: "unitedstatesofamerica",
    us: "unitedstatesofamerica",
    america: "unitedstatesofamerica",
    unitedstates: "unitedstatesofamerica",
    vietnam: "vietnam",
  };
  const target = aliases[normalized] ?? normalized;

  return countryReferences.find(
    (reference) => normalizeCountry(reference.country) === target,
  );
}

export function normalizeCountry(value: string | null | undefined) {
  return (value ?? "").toLowerCase().replace(/[^a-z0-9]+/g, "").trim();
}
