import Link from "next/link";
import type { ReactNode } from "react";
import { ClipboardCheck, FileWarning, Globe2, Scale } from "lucide-react";
import { DeleteActionButton } from "@/components/delete-action-button";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { listTasks } from "@/lib/data";
import { formatDate } from "@/lib/utils";

export default function AssessmentsPage() {
  const tasks = listTasks();

  return (
    <div className="mx-auto max-w-[1180px] space-y-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start">
        <div>
          <h1 className="text-3xl font-bold">Assessments</h1>
          <p className="mt-1 text-sm text-slate-600">
            DPIA, TIA, and LIA obligations generated by the RoPA rule engine.
          </p>
        </div>
        <Link href="/ropa/new">
          <Button>New RoPA Analysis</Button>
        </Link>
      </div>

      <div className="grid gap-5 md:grid-cols-3">
        <AssessmentMetric
          icon={<FileWarning className="h-5 w-5" />}
          label="DPIA"
          value={tasks.filter((task) => task.taskType === "DPIA").length}
          tone="red"
          href="/assessments/dpia"
        />
        <AssessmentMetric
          icon={<Globe2 className="h-5 w-5" />}
          label="TIA"
          value={tasks.filter((task) => task.taskType === "TIA").length}
          tone="yellow"
          href="/assessments/tia"
        />
        <AssessmentMetric
          icon={<Scale className="h-5 w-5" />}
          label="LIA"
          value={tasks.filter((task) => task.taskType === "LIA").length}
          tone="blue"
          href="/assessments/lia"
        />
      </div>

      <div className="grid gap-4">
        {tasks.length ? (
          tasks.map((task) => (
            <Card key={task.id}>
              <CardContent className="flex flex-col gap-4 pt-5 md:flex-row md:items-center md:justify-between">
                <div className="flex items-start gap-4">
                  <span className="flex h-10 w-10 items-center justify-center rounded bg-blue-50 text-blue-600">
                    <ClipboardCheck className="h-5 w-5" />
                  </span>
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <h2 className="font-bold">{task.title}</h2>
                      <Badge tone={task.severity === "Critical" ? "red" : "yellow"}>
                        {task.severity}
                      </Badge>
                      <Badge tone="slate">{task.status}</Badge>
                    </div>
                    <p className="mt-1 text-sm text-slate-600">{task.reason}</p>
                    <p className="mt-2 text-xs text-slate-400">
                      {task.activityName} - {task.departmentName} - due{" "}
                      {formatDate(task.dueDate)}
                    </p>
                  </div>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Link href={assessmentHref(task)}>
                    <Button variant="secondary">
                      {task.taskType === "DPIA"
                        ? "Isi DPIA"
                        : task.taskType === "TIA"
                          ? "Isi TIA"
                          : task.taskType === "LIA"
                            ? "Isi LIA"
                            : "Open"}
                    </Button>
                  </Link>
                  <DeleteActionButton
                    endpoint={`/api/tasks/${task.id}`}
                    label="Hapus"
                    confirmMessage={`Hapus assessment ${task.taskType} untuk "${task.activityName}"?`}
                  />
                </div>
              </CardContent>
            </Card>
          ))
        ) : (
          <Card>
            <CardContent className="py-10 text-center text-sm text-slate-500">
              Belum ada assessment. Tambah aktivitas RoPA untuk membuat DPIA, TIA,
              atau LIA secara otomatis.
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}

function assessmentHref(task: { id: string; taskType: string; ropaId: string }) {
  if (task.taskType === "DPIA") {
    return `/assessments/${task.id}/dpia`;
  }

  if (task.taskType === "TIA") {
    return `/assessments/${task.id}/tia`;
  }

  if (task.taskType === "LIA") {
    return `/assessments/${task.id}/lia`;
  }

  return `/ropa/${task.ropaId}/result`;
}

function AssessmentMetric({
  icon,
  label,
  value,
  tone,
  href,
}: {
  icon: ReactNode;
  label: string;
  value: number;
  tone: "red" | "yellow" | "blue";
  href: string;
}) {
  const color =
    tone === "red"
      ? "bg-red-50 text-red-600"
      : tone === "yellow"
        ? "bg-amber-50 text-amber-600"
        : "bg-blue-50 text-blue-600";

  return (
    <Link href={href}>
      <Card className="transition hover:-translate-y-0.5 hover:shadow-md">
        <CardHeader>
          <div className={`flex h-12 w-12 items-center justify-center rounded-lg ${color}`}>
            {icon}
          </div>
          <CardTitle>{label} Queue</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-4xl font-bold">{value}</div>
          <p className="text-sm text-slate-500">Generated obligations</p>
        </CardContent>
      </Card>
    </Link>
  );
}
